# Generated by Django 4.1.1 on 2022-09-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0003_prof_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prof",
            name="link",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
